
import { Selector } from "./components/selector";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
   
        <div className="flex flex-col items-center">
          <div className="max-w-screen-md min-h-[100vh] w-full flex flex-col">
            <Selector />
            {children}
          </div>
        </div>
  )
}
